# Vitesse Dark theme
# Palette based on https://github.com/antfu/vscode-theme-vitesse

# Background opacity
background_opacity 0.95

# Fonts
font_family      FantasqueSansM Nerd Font Mono
bold_font        FantasqueSansM Nerd Font Mono Bold
font_size        12.0

# Basic colors
foreground              #dbd7ca
background              #121212

# Cursor
cursor                  #dbd7ca
cursor_text_color       #181818

# Selection
selection_foreground    #dbd7ca
selection_background    #333333

# URL underline color
url_color              #6394bf

# The 16 terminal colors
color0  #393a34
color8  #777777
color1  #cb7676
color9  #cb7676
color2  #4d9375
color10 #4d9375
color3  #e6cc77
color11 #d4976c
color4  #6394bf
color12 #6394bf
color5  #d9739f
color13 #d9739f
color6  #5eaab5
color14 #5eaab5
color7  #dbd7ca
color15 #ffffff
