# Mako notification daemon configuration
# Vitesse Dark theme

font=FantasqueSansM Nerd Font Propo 12
background-color=#121212
text-color=#dbd7ca
border-color=#393a34
progress-color=over #4d9375

border-size=2
border-radius=8
padding=12
margin=10
width=300
height=150

icon-path=/usr/share/icons/hicolor
max-icon-size=48
icons=1

default-timeout=5000
ignore-timeout=0
layer=overlay
anchor=top-right

max-visible=5
history=true

actions=1
on-button-left=dismiss
on-button-middle=none
on-button-right=dismiss-all
on-touch=dismiss

[urgency=low]
border-color=#393a34

[urgency=normal]
border-color=#393a34

[urgency=critical]
border-color=#cb7676
background-color=#181818
text-color=#dbd7ca
