general {
    col.active_border = rgba(e6b450ee) rgba(deae4dee) 45deg
    col.inactive_border = rgba(686868aa)
}

group {
    col.border_active        = rgb(e6b353)
    col.border_inactive      = rgb(1b1f29)
    col.border_locked_active = rgb(fdb04c)

    groupbar {
        col.active      = rgb(e6b353)
        col.inactive    = rgb(1b1f29)
        text_color      = rgb(bfbdb6)
        font_family     = Iosevka Nerd Font
        font_size       = 14
    }
}

decoration {
    shadow {
        color = rgba(0a0a0aee)
    }
}
