general {
    col.active_border = rgba(d79921ee) rgba(d65d0eee) 45deg
    col.inactive_border = rgba(504945aa)
}

group {
    col.border_active        = rgb(a9b665)
    col.border_inactive      = rgb(3c3836)
    col.border_locked_active = rgb(d8a657)

    groupbar {
        col.active      = rgb(3c3836)
        col.inactive    = rgb(1d2021)
        text_color      = rgb(d4be98)
    }
}

decoration {
    shadow {
        color = rgba(1a1a1aee)
    }
}
