background {
    monitor =
    path = ~/Pictures/Wallpapers/forest--darkblue.jpg
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(4fbfff)
    inner_color = rgb(141821)
    font_color = rgb(bfbdb6)
    fade_on_empty = true
    placeholder_text = <i>Password</i>
    check_color = rgb(4fbfff)
    fail_color = rgb(f06b73)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = FiraCode Nerd Font
    color = rgba(bfbdb6ff)
    position = 0, 100
    halign = center
    valign = center
}
