background {
    monitor =
    path = ~/Pictures/Wallpapers/dark-vines--darkgreen.jpg
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(4d9375)
    inner_color = rgb(181818)
    font_color = rgb(dbd7ca)
    fade_on_empty = true
    placeholder_text = <i>Password</i>
    check_color = rgb(4d9375)
    fail_color = rgb(cb7676)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = FantasqueSansM Nerd Font Propo
    color = rgba(dbd7caff)
    position = 0, 100
    halign = center
    valign = center
}
