general {
    col.active_border = rgba(4d9375ee) rgba(6394bfee) 45deg
    col.inactive_border = rgba(393a34aa)
}

group {
    col.border_active        = rgb(4d9375)
    col.border_inactive      = rgb(181818)
    col.border_locked_active = rgb(d4976c)

    groupbar {
        col.active      = rgb(4d9375)
        col.inactive    = rgb(181818)
        text_color      = rgb(dbd7ca)
        font_family     = FantasqueSansM Nerd Font
        font_size       = 14
    }
}

decoration {
    shadow {
        color = rgba(000000ee)
    }
}
