background {
    monitor =
    path = ~/Pictures/leaves-hard.png
    blur_passes = 2
    blur_size = 7
}

input-field {
    monitor =
    size = 300, 50
    outline_thickness = 2
    outer_color = rgb(a9b665)
    inner_color = rgb(32302f)
    font_color = rgb(d4be98)
    fade_on_empty = true
    placeholder_text = <i>Password</i>
    check_color = rgb(a9b665)
    fail_color = rgb(ea6962)
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>
    position = 0, -100
    halign = center
    valign = center
}

label {
    monitor =
    text = $TIME
    font_size = 64
    font_family = FiraCode Nerd Font
    color = rgba(d4be98ff)
    position = 0, 100
    halign = center
    valign = center
}
