#add_newline = false§
format = """
[┌](bold green) $time | $username$hostname: $directory \
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$package\
$cmake\
$nodejs\
$python\
$rust\
$env_var\
$status\
$jobs
[└─](bold green) $character
""" 

command_timeout = 200 

[directory]
truncate_to_repo = false
format = "[$path]($style)"
style = "bold cyan"

[character]                           
success_symbol = "[\\(\\)](bold green)"
error_symbol = "[\\(\\)](bold red)" 
format = "$symbol "

[time]
disabled = false
format = "[$time]($style)"
style = "bold white"

[username]
show_always = true
format = "[$user]($style)"
style_root = "bold bright-yellow"
style_user = "bright-yellow"


[hostname]
ssh_only = true
disabled =  false
format = "@[$hostname]($style)"
style = "green"

